cc_binary(
    name = "FaceRecog",
    srcs = ["FaceRecog.cpp"],
    deps = [
        "//third_party:opencv2",
    ],
    copts = [
        "-Ithird_party/usr/local/include",
        "-Ithird_party/usr/include/c++/4.8",
        "-Ithird_party/usr/include/x86_64-linux-gnu/c++/4.8",
    ],
)

cc_binary(
    name = "BodyRecog",
    srcs = ["BodyRecog.cpp"],
    deps = [
        "//third_party:opencv2",
    ],
    copts = [
        "-Ithird_party/usr/local/include",
        "-Ithird_party/usr/include/c++/4.8",
        "-Ithird_party/usr/include/x86_64-linux-gnu/c++/4.8",
    ],
)
