bind(
    name = "protobuf_clib",
    actual = "//google/protobuf:protobuf",
)

bind(
    name = "protobuf_compiler",
    actual = "//google/protobuf:protoc_lib",
)

bind(
    name = "gtest",
    actual = "//google:googlemock",
)

bind(
    name = "gtest_main",
    actual = "//google:googlemock_main",
)

bind(
    name = "zlib",
    actual = "//third_party:zlib",
)

bind(
    name = "libssl",
    actual = "//third_party:libssl",
)
